---
- name: Backup /etc/hosts
  ansible.builtin.copy:
    src: /etc/hosts
    dest: /etc/hosts.bak
    remote_src: yes
    force: no

- name: Add entries to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    create: yes
  loop:
    - "1.2.3.4 host1"
    - "3.4.2.1 host2"
    - "5.6.3.2 host3"